### ISSUE TITLE
Add an auto-rename feature like advertised on website

### ISSUE THREAD

**Issue by Mikaz-fr** [gielcobben/Caption#19]
Either the auto-rename is not available or I didn't find how to configure it, but I was hopping to use it.

That would be super cool to have configurable file/subtitle renaming.

**Comment by gattilorenz** [comment]
If you drop a video file over caption, the subtitles are automatically renamed, aren't they?

**Comment by Mikaz-fr** [comment]
Ah my bad I guess I didn't understand the feature. I thought it would rename both the input video file and the subtitle to something I wanted/configured. I do not know the original subtitle name so I cannot judge if it was renamed or if it was the same name to begin with.
Nevermind then.

**Comment by gielcobben** [comment]
I'll close this issue for now.
