### ISSUE TITLE
ESLint configuration

### ISSUE THREAD

**Issue by jeroenrinzema** [gielcobben/Caption#28]
I am getting at the moment 82 linter errors and a lot more warnings when i am opening
`app/containers/Home.js`
Maybe do we have to improve the linter configuration to make sure that those errors are valid.
For example do we want the indenting to be spaces or tabs and how many etc.

**Comment by vernondegoede** [comment]
Good suggestion! However, we decided to use Prettier instead of ESLint in Caption v2.
