### ISSUE TITLE
Separate node module with core functionality.

### ISSUE THREAD

**Issue by ritz078** [gielcobben/caption#32]
Would you like to create a separate node module for this ? This seems great and I would love to use this in https://github.com/ritz078/snape . Let me know if you need any help.

**Comment by vernondegoede** [comment]
Related to https://github.com/gielcobben/Caption/issues/31.

**Comment by vernondegoede** [comment]
We've completed the abstraction of our core logic into a separate module. We module can be found at https://github.com/gielcobben/caption-core.

Currently `caption-core` supports:
- Downloading subtitles
- Searching by files
- Searching subtitles by search query (supports multiple sources)
