### ISSUE TITLE
Don't add non video files to list of files

### ISSUE THREAD

**Issue by nicolas-besnard** [gielcobben/caption#54]
Right now, if you add a directory to Caption, it'll show all the files in the directory.

Shouldn't we have a whitelist?

**Comment by gielcobben** [comment]
It's fixed in v2, coming next week!

**Comment by nicolas-besnard** [comment]
Great! If you need beta-tester or a developer help, I’m free :)

**Comment by nicolas-besnard** [comment]
@vernondegoede any news on 2.0 :) ?

**Comment by vernondegoede** [comment]
@nicolas-besnard The new Caption will land next week :) 

If you like you can download the beta release from Github Releases. Let us know what you think!

**Comment by nicolas-besnard** [comment]
I got an error when adding 22 directories.

![Uploading Screen Shot 2017-11-25 at 10.26.50 pm.png…]()

**Comment by vernondegoede** [comment]
The screenshot doesn't work for me. Can you try adding it again?

**Comment by nicolas-besnard** [comment]
Comment updated!

**Comment by vernondegoede** [comment]
Thanks for your help! If you find any other issues, let us know 🙌
