### ISSUE TITLE
I open the app but it just a blank windows

### ISSUE THREAD

**Issue by hoangvn2404** [gielcobben/caption#75]
I'm using Macbook OS Sierra (MQLT2)
I just download Caption version 2 and when I open it is just a blank windows and I can not do anything with it.

I had record the reproduce here
http://recordit.co/0MYv0rgL5Z

**Comment by gielcobben** [comment]
There seems to be a bug when you rename the app. I think the app works if you just call is Caption.app We're working on a fix.

**Comment by hoangvn2404** [comment]
thanks you, I rename the application and it work now
