### ISSUE TITLE
Caption changes preferred app to open MKV-files to Caption

### ISSUE THREAD

**Issue by remcovanravenswaaij** [gielcobben/caption#77]
- [X ] I have searched the [issues](https://github.com/gielcobben/Caption/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Caption should not change the default program of MKV-files.

--none, see bug above--

## Current Behavior

When dragging an MKV-video file to Caption window it changes the default program to open this MKV file to Caption. 

## Steps to Reproduce (for bugs)

1. I open Caption (version 2.0.0) on my MacBook Pro, Mac OSX 10.13.2 and leave it the active program.
2. I drag an MKV-file from a already open Finder window to the Caption window. 
3. Caption does it thing great, it finds subtitles in Dutch.
4. I close the Caption program by CMD-Q.
5. I double click on a random MKV-file and Caption opens to start searching for subtitles (I expected VLC to open the video file)

## Context

I have to change the default program back to VLC by right-click and choose 'Open with..' and select the 'Always open this program' selection.

## Your Environment

| Tech           | Version |
|----------------|---------|
| app version    |    2.0.0     |
| OS             |    10.13.2     |
| VLC            |     2.2.1   |

**Comment by nunorafaelrocha** [comment]
Same bug for MP4 files...

**Comment by vernondegoede** [comment]
Thanks! A fix will arrive in a few days.

**Comment by vmorris1959** [comment]
I had the same problem and It's good to hear the bug will be fixed, but how do I get back the VLC icon for MKVs? I set it back to open with VLC but the MKVs still show the Caption icon :(

**Comment by manishimo212** [comment]
Yeah it does it for most video formats. Quite frustrating :( Is there an update for the fix, team?

**Comment by gielcobben** [comment]
We just released version [2.0.1](https://github.com/gielcobben/caption/releases/tag/v2.0.1) of Caption. This update fixes the issue where caption is the default application for video files. Let us know if you have any questions or other issues.
