### ISSUE TITLE
Overflow bug on some devices

### ISSUE THREAD

**Issue by gielcobben** [gielcobben/Caption#8]
Some people have this overflow issue where they have vertical and horizontal scrollbars. 

**Seen on:**
- OS X 10.11.0
- MacOS 10.12.2
- MacOS 10.12.3

**Image:**
![image](https://cloud.githubusercontent.com/assets/2663212/22819553/f119b248-ef72-11e6-86e5-baf461ed39a5.png)

**Comment by mattijsbliek** [comment]
This bug likely only appears when you have a third party mouse connected. See the 'show scrollbars' setting in System Preferences › General. Switch this setting to "Always" to replicate the bug.

![screen shot 2017-02-13 at 16 36 15]
(https://cloud.githubusercontent.com/assets/2960795/22889899/f0b1445c-f20a-11e6-8211-f896536fbfed.png)

**Comment by gielcobben** [comment]
Damn @mattijsbliek. As always, Thanks. 🙏🏻
