### ISSUE TITLE
Open With in Finder is not working anymore since the last update

### ISSUE THREAD

**Issue by gustavomd** [gielcobben/caption#87]
- [x] I have searched the [issues](https://github.com/gielcobben/Caption/issues) of this repository and believe that this is not a duplicate.

## Current Behavior

Open With in Finder is not working anymore since the last update. It worked before. You could even send files to Caption with Lauchbar and Alfred

## Steps to Reproduce (for bugs)
1. in Finder, secondary click a file and try Open With menu.
## Your Environment

| Tech           | Version |
|----------------|---------|
| app version    |  2.01       |
| OS             |  10.13.2       |
| etc            |         |

**Comment by vernondegoede** [comment]
We removed this on purpose, since it also changed the default program for MKV-files into Caption instead of a video player.

**Comment by gustavomd** [comment]
damn, it was a useful feature.
is there a way to work around that?

**Comment by matcornic** [comment]
@gustavomd @vernondegoede with a workaround, it could be done when a CLI is available (see #31). You could use the app *Service Automator* by following the same kind of instructions I did for my [Subify](https://github.com/matcornic/subify) CLI. It would not be plug and play, but it works perfectly.

**Comment by gustavomd** [comment]
Thanks Mathieu, that's a very elegant solution.
